"""add unique constraint mission waypoint order

Revision ID: a0d89278edaf
Revises: 38223928cb6a
Create Date: 2025-11-25 00:50:10.361913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d89278edaf'
down_revision = '38223928cb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_waypoints', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_mission_waypoint_order_per_mission', ['mission_id', 'order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_waypoints', schema=None) as batch_op:
        batch_op.drop_constraint('uq_mission_waypoint_order_per_mission', type_='unique')

    # ### end Alembic commands ###
