"""Add drone_specs table and relation

Revision ID: 1bb68d74c094
Revises: a0d89278edaf
Create Date: 2025-11-29 18:29:32.105178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb68d74c094'
down_revision = 'a0d89278edaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_specs',
    sa.Column('spec_id', sa.UUID(), nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('flight_controller', sa.String(length=255), nullable=True),
    sa.Column('motor', sa.String(length=255), nullable=True),
    sa.Column('esc', sa.String(length=255), nullable=True),
    sa.Column('propeller', sa.String(length=100), nullable=True),
    sa.Column('battery', sa.String(length=255), nullable=True),
    sa.Column('gps_module', sa.String(length=255), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('max_flight_time_min', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.drone_id'], ),
    sa.PrimaryKeyConstraint('spec_id'),
    sa.UniqueConstraint('drone_id')
    )
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'flight_sessions', ['session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('drone_specs')
    # ### end Alembic commands ###
