"""add drone_id to missions

Revision ID: 38223928cb6a
Revises: e92e3f861ffe
Create Date: 2025-11-25 00:18:00.501924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38223928cb6a'
down_revision = 'e92e3f861ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'drones', ['drone_id'], ['drone_id'])

    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('telemetry_data_time_idx'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('telemetry_data_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('drone_id')

    # ### end Alembic commands ###
