"""add drone_id to missions

Revision ID: 38223928cb6a
Revises: e92e3f861ffe
Create Date: 2025-11-25 00:18:00.501924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38223928cb6a'
down_revision = 'e92e3f861ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key('missions_drone_id_fkey', 'drones', ['drone_id'], ['drone_id'])

    op.execute('DROP INDEX IF EXISTS telemetry_data_time_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'CREATE INDEX IF NOT EXISTS telemetry_data_time_idx ON telemetry_data (time DESC)'
    )

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint('missions_drone_id_fkey', type_='foreignkey')
        batch_op.drop_column('drone_id')

    # ### end Alembic commands ###
