"""Initial migration 14 tables

Revision ID: e92e3f861ffe
Revises: 
Create Date: 2025-11-20 18:45:55.446767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92e3f861ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PRE_FLIGHT', 'POST_FLIGHT', name='checklisttype'), nullable=False),
    sa.PrimaryKeyConstraint('checklist_id')
    )
    op.create_table('drones',
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('lora_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('READY', 'MAINTENANCE', 'FLYING', 'RETIRED', name='dronestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('drone_id'),
    sa.UniqueConstraint('lora_id')
    )
    op.create_table('geofences',
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SAFE_ZONE', 'NO_FLY_ZONE', name='geofencetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('geofence_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PILOT', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('checklist_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('item_text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.checklist_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('geofence_points',
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.geofence_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('maintenance_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('serviced_by_user_id', sa.UUID(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.drone_id'], ),
    sa.ForeignKeyConstraint(['serviced_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('missions',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('mission_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='missionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_table('flight_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('pilot_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('LIVE', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.drone_id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('mission_checklists',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.checklist_id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.PrimaryKeyConstraint('mission_id', 'checklist_id')
    )
    op.create_table('mission_geofences',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.geofence_id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.PrimaryKeyConstraint('mission_id', 'geofence_id')
    )
    op.create_table('mission_waypoints',
    sa.Column('waypoint_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.PrimaryKeyConstraint('waypoint_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('LOW_BATTERY', 'GEOFENCE_BREACH', 'SIGNAL_LOST', 'MISSION_ERROR', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['flight_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('telemetry_data',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['flight_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('time', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_data')
    op.drop_table('alerts')
    op.drop_table('mission_waypoints')
    op.drop_table('mission_geofences')
    op.drop_table('mission_checklists')
    op.drop_table('flight_sessions')
    op.drop_table('missions')
    op.drop_table('maintenance_logs')
    op.drop_table('geofence_points')
    op.drop_table('checklist_items')
    op.drop_table('users')
    op.drop_table('geofences')
    op.drop_table('drones')
    op.drop_table('checklists')
    # ### end Alembic commands ###
